sudo: false

notifications:
  email:
    - bloublou2014@gmail.com
language: node_js
node_js:
  - "iojs"
  - "4.0"
  - "5.0"
branches:
  only:
    - master
services:
  - redis-server
  - elasticsearch
